---
- hosts: veos01

  vars:
    params:
      - { name: Ethernet1, description: disabled by template }
      - { name: Ethernet2, description: disabled by template }
      - { name: Ethernet3, description: disabled by template }
      - { name: Ethernet4, description: disabled by template }
      - { name: Ethernet5, description: disabled by template }
      - { name: Ethernet6, description: disabled by template }
      - { name: Ethernet7, description: disabled by template }

  tasks:
    - name: configure eos devices
      net_config:
        src: config.j2
        authorize: yes
      register: output
      connection: local

    - debug: var=output

- hosts: ops01
  gather_facts: no

  vars:
    params:
      - { name: 1, description: disabled by template }
      - { name: 2, description: disabled by template }
      - { name: 3, description: disabled by template }
      - { name: 4, description: disabled by template }
      - { name: 5, description: disabled by template }
      - { name: 6, description: disabled by template }
      - { name: 7, description: disabled by template }

  tasks:
    - name: configure ops devices
      net_config:
        src: config.j2
      register: output
      connection: local

    - debug: var=output

- hosts: nxos01
  gather_facts: no

  vars:
    params:
      - { name: Ethernet2/1, description: disabled by template }
      - { name: Ethernet2/2, description: disabled by template }
      - { name: Ethernet2/3, description: disabled by template }
      - { name: Ethernet2/4, description: disabled by template }
      - { name: Ethernet2/5, description: disabled by template }

  tasks:
    - name: configure nxos devices
      net_config:
        src: config.j2
        provider: nxos
      register: output
      delegate_to: virl
      connection: local

    - debug: var=output

- hosts: ios01
  gather_facts: no

  vars:
    params:
      - { name: GigabitEthernet2/1, description: disabled by template }
      - { name: GigabitEthernet2/2, description: disabled by template }
      - { name: GigabitEthernet2/3, description: disabled by template }
      - { name: GigabitEthernet2/4, description: disabled by template }
      - { name: GigabitEthernet2/5, description: disabled by template }

  tasks:
    - name: configure ios devices
      net_config:
        src: config.j2
        provider: ios
      register: output
      delegate_to: virl
      connection: local

    - debug: var=output

